### ISSUE TITLE
off-cluster reds port is string

### ISSUE THREAD

**Issue by rimusz** [deis/redis#9] opened 2016-12-01 14:04 UTC
`port: "6379"`
 it should be int `port: 6379`

**Comment by rimusz** [comment] 2016-12-01 14:16
hmm, logger still showing:
```
deis-logger-3543932191-enyq4
2016/12/01 14:09:01 config error: envconfig.Process: assigning LOGGER_DEIS_LOGGER_REDIS_SERVICE_PORT to DEIS_LOGGER_REDIS_SERVICE_PORT: converting 'redis port' to type int:
```

**Comment by bacongobbler** [comment] 2016-12-01 14:32
This is intended by design, as environment variable values set in a k8s manifest must be a string.

I'll see if I can reproduce this.

**Comment by rimusz** [comment] 2016-12-01 14:34
ok, so logger is not happy with the off-cluster redis

**Comment by vdice** [comment] 2016-12-01 16:42
@rimusz off-cluster redis will only work in the forthcoming `v2.9.0` chart.  To confirm, you can install the k/helm chart by adding the workflow-staging repo:
```
helm repo add workflow-staging https://charts.deis.com/workflow-staging
helm install workflow-staging/workflow --version v2.9.0 --namespace deis
```

**Comment by rimusz** [comment] 2016-12-01 17:44
ah, I see
when the v2.9.0 going to be released?

**Comment by bacongobbler** [comment] 2016-12-01 18:02
hopefully today.

Let's close this ticket out as resolved for now, but please re-open if you're seeing this issue on master/v2.9.0.

**Closed as completed by bacongobbler** 2016-12-01 18:02 UTC
